markdown: kramdown
title: kvaky's blog
description: adventures, thoughts, etc.
theme: minima
author:
  name: Peter KvaÄkay
  email: "peter.kvackay@gmail.com"

instagram_username: kvaky
minima:
  date_format: "%Y-%m-%d"
