markdown: kramdown
title: kvaky's blog
description: adventures, thoughts, etc.
theme: minima
author: Peter KvaÄkay
email: "peter.kvackay@gmail.com"

plugins: 
  - jekyll-feed

collections:
  drafts:
    output: true
defaults:
  -
    scope:
      path: ""
      type: drafts
    values:
      layout: draft
  
show_excerpts: true

instagram_username: kvaky
facebook_username: peter.kvackay
minima:
  date_format: "%Y-%m-%d"
